name: Build docker image and deploy to WMD docker servers

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
 deploy:
    name: "Deploy to ITAS WMD server"
    runs-on: wmd-dockerdev

    steps:
      - name: Copy source code files
        uses: actions/checkout@v2

      - name: Test files are visible
        run: |
          whoami
          ls -lah

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
