name: Build, Push, and Scan Docker Image

on:
 push:
    branches:
      - master

jobs:
 build-push-scan:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out code
      uses: actions/checkout@v2

    # Log in to Docker Hub using the provided username and password
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image and push it to Docker Hub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: joshgervais/nodegoat:latest

    # Run Semgrep to generate a SARIF report and upload it directly to GitHub Code Scanning
    - name: Run Semgrep and upload SARIF report to GitHub Code Scanning
      run: |
        # Run Semgrep and output the SARIF report to a temporary file
        docker run --rm -v "${{ github.workspace }}:/github/workspace" returntocorp/semgrep semgrep --config="p/r2c-ci" --sarif /github/workspace > semgrep.sarif
        # Upload the SARIF report to GitHub Code Scanning
        echo "::set-output name=sarif::$(cat semgrep.sarif)"
      id: semgrep

    # Upload the Semgrep SARIF report to GitHub Code Scanning
    - name: Upload Semgrep SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_content: ${{ steps.semgrep.outputs.sarif }}

    # Run Snyk to check for vulnerabilities and generate a SARIF report
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        command: test
        args: --sarif-file-output=./artifacts/snyk-results.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # Upload the Snyk SARIF report to GitHub Code Scanning
    - name: Upload Snyk SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./artifacts/snyk-results.sarif
