name: Build, Push, and Scan Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out code
      uses: actions/checkout@v2

    # Log in to Docker Hub using the provided username and password
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image and push it to Docker Hub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: joshgervais/nodegoat:latest

    # Post a message to Discord when the build and push stage completes
    - name: Discord Notification - Build and Push
      if: always()
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        username: ${{ github.repository }}
        avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
        embed-title: "Docker Build and Push completed"
        embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: "The Docker image has been built and pushed to Docker Hub."
        embed-author-name: "${{ github.triggering_actor }}"

  semgrep-sast-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v2

      # Run Semgrep and generate SARIF report
      - name: Run Semgrep and generate SARIF report
        run: |
          semgrep \
          --sarif --output semgrep-sast.sarif \
          --metrics=off \
          --config="p/r2c-ci"

      # Save Semgrep SARIF report
      - name: Save Semgrep SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif

      # Post a message to Discord when the Semgrep SAST scan completes
      - name: Discord Notification - Semgrep SAST
        if: always()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Semgrep SAST scan completed"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "The Semgrep SAST scan has completed. Download the SARIF report: ${{ steps.upload-artifact.outputs.browser_download_url }}"
          embed-author-name: "${{ github.triggering_actor }}"

  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: test
          args: --sarif-file-output=snyk-results.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      # Save Snyk SARIF report
      - name: Save Snyk SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: snyk-sca.sarif
          path: snyk-results.sarif

      # Post a message to Discord when the Snyk scan completes
      - name: Discord Notification - Snyk Scan
        if: always()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Snyk scan completed"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "The Snyk scan has completed. Download the SARIF report: ${{ steps.upload-artifact.outputs.browser_download_url }}"
          embed-author-name: "${{ github.triggering_actor }}"
