name: Build, Push, and Scan Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    
    steps:
    # Check out the repository code
    - name: Check out code
      uses: actions/checkout@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: joshgervais/nodegoat:latest

    # Run Semgrep for SAST
    - name: Run Semgrep and generate SARIF report
      run: |
        docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep --config="p/r2c-ci" --sarif --output=semgrep.sarif /src

    # Upload Semgrep SARIF report
    - name: Upload Semgrep SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: semgrep.sarif

    # Run Snyk for SCA
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        command: test
        args: --sarif-file-output=snyk-results.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # Upload Snyk SARIF report
    - name: Upload Snyk SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk-results.sarif
