name: Build, Push, and Scan Docker Image

on:
 push:
    branches:
      - master

jobs:
 build-push-scan:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out code
      uses: actions/checkout@v2

    # Log in to Docker Hub using the provided username and password
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image and push it to Docker Hub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: joshgervais/nodegoat:latest

    # Run Semgrep to generate a SARIF report and save it in the GitHub workspace
    - name: Run Semgrep and generate SARIF report
      run: |
        # Run Semgrep and output the SARIF report to the GitHub workspace
        semgrep --config="p/r2c-ci" --sarif --output=${{ github.workspace }}/semgrep.sarif .

    # List the contents of the GitHub workspace to verify that the Semgrep SARIF report was created
    - name: List contents of GitHub workspace after Semgrep
      run: ls -la ${{ github.workspace }}

    # Upload the Semgrep SARIF report to GitHub Code Scanning
    - name: Upload Semgrep SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/semgrep.sarif

    # Run Snyk to check for vulnerabilities and generate a SARIF report
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        command: test
        args: --sarif-file-output=${{ github.workspace }}/snyk-results.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # List the contents of the GitHub workspace to verify that the Snyk SARIF report was created
    - name: List contents of GitHub workspace after Snyk
      run: ls -la ${{ github.workspace }}

    # Upload the Snyk SARIF report to GitHub Code Scanning
    - name: Upload Snyk SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/snyk-results.sarif

    # Upload all SARIF reports in the GitHub workspace to the GitHub Actions artifacts
    - name: Upload SARIF reports to GitHub workspace
      uses: actions/upload-artifact@v2
      with:
        name: security-reports
        path: ${{ github.workspace }}
