name: Build, Push, and Scan Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: joshgervais/nodegoat:latest

    - name: Run Semgrep and generate SARIF report
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        docker run --rm -v "${{ github.workspace }}:/github/workspace" returntocorp/semgrep semgrep --config="p/r2c-ci" --sarif --output=/github/workspace/artifacts/semgrep.sarif /github/workspace

    - name: Upload Semgrep SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/artifacts/semgrep.sarif

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        command: test
        args: --sarif-file-output=${{ github.workspace }}/artifacts/snyk-results.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Upload Snyk SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/artifacts/snyk-results.sarif

    - name: Upload SARIF reports to artifacts directory
      uses: actions/upload-artifact@v2
      with:
        name: security-reports
        path: ${{ github.workspace }}/artifacts/
