name: Build, Push, and Scan Docker Image

on:
 push:
    branches:
      - master

jobs:
 build-push-scan:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out code
      uses: actions/checkout@v2

    # Print the current working directory
    - name: Print current working directory
      run: pwd

    # Print the absolute path of the 'artifacts' directory
    - name: Print absolute path of artifacts directory
      run: echo $(pwd)/artifacts

    # Log in to Docker Hub using the provided username and password
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image and push it to Docker Hub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: joshgervais/nodegoat:latest

    # Ensure the artifacts directory exists
    - name: Ensure the artifacts directory exists
      run: mkdir -p ${{ github.workspace }}/artifacts

    # Run Semgrep to generate a SARIF report and save it in the 'artifacts' directory
    - name: Run Semgrep and generate SARIF report
      run: |
        docker run --rm -v "${{ github.workspace }}:/github/workspace" returntocorp/semgrep semgrep --config="p/r2c-ci" --sarif --output=${{ github.workspace }}/artifacts/semgrep.sarif /github/workspace

    # List the contents of the 'artifacts' directory to verify that the Semgrep SARIF report was created
    - name: List contents of artifacts directory after Semgrep
      run: ls -la ./artifacts

    # Upload the Semgrep SARIF report to GitHub Code Scanning
    - name: Upload Semgrep SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./artifacts/semgrep.sarif

    # Run Snyk to check for vulnerabilities and generate a SARIF report
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        command: test
        args: --sarif-file-output=./artifacts/snyk-results.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # List the contents of the 'artifacts' directory to verify that the Snyk SARIF report was created
    - name: List contents of artifacts directory after Snyk
      run: ls -la ./artifacts

    # Upload the Snyk SARIF report to GitHub Code Scanning
    - name: Upload Snyk SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./artifacts/snyk-results.sarif

    # Upload all SARIF reports in the 'artifacts' directory to the GitHub Actions artifacts
    - name: Upload SARIF reports to artifacts directory
      uses: actions/upload-artifact@v2
      with:
        name: security-reports
        path: ./artifacts
